# Generated by Django 5.2.1 on 2025-05-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacite', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('etage', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPEE', 'Occupée'), ('NETTOYAGE', 'En nettoyage'), ('MAINTENANCE', 'En maintenance')], default='DISPONIBLE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('type_chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chambres.typechambre')),
            ],
        ),
        migrations.CreateModel(
            name='ChambreEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('etat', models.CharField(choices=[('BON', 'Bon état'), ('MOYEN', 'État moyen'), ('MAINTENANCE', 'En maintenance'), ('A_REMPLACER', 'À remplacer')], default='BON', max_length=12)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambres.chambre')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambres.equipement')),
            ],
            options={
                'verbose_name': 'Équipement de chambre',
                'verbose_name_plural': 'Équipements de chambre',
                'unique_together': {('chambre', 'equipement')},
            },
        ),
    ]
