# Generated by Django 5.2.1 on 2025-05-08 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
            ],
        ),
    ]
